### ISSUE TITLE
Could not load manifest when 

### ISSUE THREAD

**Issue by coonsmatthew** [csirtgadgets/bearded-avenger-chrome#2]
I get an issue when I try to load the plugin. 

Chrome says: 
"Error loading extension" 
Failed to load extension from: ~/Downloads/bearded-avenger-chrome-master
Manifest file is missing or unreadable.

Second question, will this extension be available on the Chrome store in the future? 

Thanks.

**Comment by wesyoung** [comment]
are you loading the src/ directory? (where the manifest is located?)

https://github.com/csirtgadgets/bearded-avenger-chrome/tree/master/src

the top level dir is just for packaging it for upload to chrome store... and yes. once we've had a few cycles with it it'll find it's way there- just prototyped it quickly- need to make sure the bugs are gone.

**Comment by coonsmatthew** [comment]
Ha, seems it was user error. I think I've run into this issue before. Sorry about the noise!
